version: "3"
services:

  freeciv-web:
    image: freeciv/freeciv-val
    build: .
    container_name: tnt.val
    command: ["sleep", "infinity"]
    volumes:
      - "data:/var/lib/tomcat8/webapps/data"
    ports:
            #      - "8080:8081"
            #      - "4002"
            #      - "6000-6009:6000-6009"
            #      - "7000-7009:7000-7009"
            #      - "8888:8080"
      - "9595:80"
    user: docker

volumes:
  data:
